### ISSUE TITLE
Issue on Samsung devices

### ISSUE THREAD

**Issue by mmicoe** [Poing-Studios/godot-admob-android#136]
Issue using on some Samsung devices:
Using Godot 3.5
Admod Poing Studios 3.5

Issue on SmartPhone:
Device: Samsung Galaxy A52s 5G
Android: 12

If Admob is Enabled I get this issue:

2022-09-09 20:24:19.100 28440-28473/com.multiplicationworld E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.multiplicationworld, PID: 28440
    java.lang.IllegalArgumentException: com.multiplicationworld: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

**Additional context**
The most curious thing is that I have tested it with an old Samsung tablet and it works fine.
Using Tablet Samsung SM-T580
Android: 8.1.0, 
Admob works fine!

Please, what version of Admob can I use on Godot 3.5?

All the best!
Mauro

**Comment by mmicoe** [comment]
OK.
I readt he previous post:

Adding this line:

[dependencies]
remote=["com.google.android.gms:play-services-ads:21.1.0", "com.google.android.ump:user-messaging-platform:2.0.0"]

on Admob.gdap, it works fine!

Please, update the pluging!

All the best!
Thanks for your work!

**Comment by gumaciel** [comment]
Thank you for testing the implementation of #126, I will update the plugin and close the Issue!
